version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - airflow-network

  airflow:
    image: apache/airflow:latest
    restart: always
    container_name: airflow
    entrypoint: ["bash", "-c"]
    command:
      - "/opt/airflow/airflow_setup.sh"
    environment:
      - PYTHONPATH=/opt/airflow
      - HOST=${HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_DB=${APP_DB}
      - AIRFLOW_DB=${AIRFLOW_DB}
      - IPO_CALENDAR_DB=${IPO_CALENDAR_DB}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${AIRFLOW_DB}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY}
      - FMP_KEY=${FMP_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow_setup.sh:/opt/airflow/airflow_setup.sh
      - ./app:/opt/airflow/app
      - ./dba:/opt/airflow/dba
    depends_on:
      - postgres
    networks:
      - airflow-network

networks:
  airflow-network:


