version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - airflow-network

  airflow:
    image: apache/airflow:latest
    restart: always
    container_name: airflow
    entrypoint: ["bash", "-c"]
    command:
      - "/opt/airflow/airflow_setup.sh"
    environment:
      - FLASK_APP=${FLASK_APP}
      - DB_HOST=${HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - AIRFLOW_DB=${AIRFLOW_DB}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - APP_DB=${APP_DB}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow_setup.sh:/opt/airflow/airflow_setup.sh
    depends_on:
      - postgres
    networks:
      - airflow-network

networks:
  airflow-network:


