name: Run Unit Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      TEST_DB_URL: postgresql://user:password@localhost:5432/test_db
      HOST: localhost
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Run dba tests
      run: |
        poetry run pytest ./dba/test_dba -vvv

    # - name: Run app tests
    #   run: |
    #     pip install -U email-validator
    #     poetry run pytest ./app/test_app -vvv
